# Covid stochastic model configuration

ProcessData:
  date_range:
    - 2020-11-20
    - 2021-02-12
  mobility_matrix: data/mergedflows.csv
  population_size: data/c2019modagepop.csv
  commute_volume:   # Can be replaced by DfT traffic flow data - contact authors <c.jewell@lancaster.ac.uk>
  geopackage: data/UK2019mod_pop.gpkg
  
  CasesData:
    input: csv
    address: data/latest_line_list.zip
    pillars:
      - Pillar 1  # Capability to filter Pillar 1 and 2 testing data from PHE confidential line listing
    measure: specimen  # Capability to filter date of test report from PHE confidential line listing
    format: phe
 
  AreaCodeData:
    input: json
    address:  "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LAD_APR_2019_UK_NC/FeatureServer/0/query?where=1%3D1&outFields=LAD19CD,LAD19NM&returnGeometry=false&returnDistinctValues=true&orderByFields=LAD19CD&outSR=4326&f=json"
    format: ons
    regions:
      - E  # England

Mcmc:
  dmax: 84  # Max distance to move events
  nmax: 50  # Max num events per metapopulation/time to move
  m: 1      # Number of metapopulations to move
  occult_nmax: 15  # Max number of occults to add/delete per metapop/time
  num_event_time_updates: 380  # Num event and occult updates per sweep of Gibbs MCMC sampler.
  num_bursts: 100  # Number of MCMC bursts of `num_burst_samples` 
  num_burst_samples: 200  # Number of MCMC samples per burst
  thin: 20  # Thin MCMC samples every `thin` iterations
  num_adaptation_iterations: 1000

ThinPosterior:  # Post-process further chain thinning HDF5 -> .pkl.
  start: -10000
  end: 
  by: 10

Geopackage:  # covid.tasks.summary_geopackage
  base_geopackage: data/UK2019mod_pop.gpkg
  base_layer: UK2019mod_pop_xgen