#!/bin/bash

########################################################
# Name: pipeline.sge				       #
# Created: 2021-02-07				       #
# Author: Chris Jewell <c.jewell@lancaster.ac.uk>      #
# License: MIT					       #
# Copyright: Chris Jewell 2021			       #
# Purpose:  Specify covid job to run on an SGE cluster #
#           with GPUS.                                 #
########################################################

#$ -S /bin/bash
#$ -P chicas
#$ -q medium
#$ -l ngpus=1
# -l ncpus=4
#$ -l h_vmem=64G
#$ -l h_rt=24:00:00
#$ -j y
#$ -cwd
#$ -M c.jewell@lancaster.ac.uk
#$ -m bea

error_exit() {
    MSG=${1:-"Unknown Error"}
    echo $MSG 1>&2
    exit 1
}


while getopts 'c:d:s:r:' OPTION; do
    case "$OPTION" in
	c)
	    echo "Config: ${OPTARG}"
	    arg_config=${OPTARG}
	    ;;
	d)
	    echo "Date: ${OPTARG}"
	    arg_date=${OPTARG}
	    ;;
	s)
	    echo "Results staging dir: ${OPTARG}"
	    arg_staging_dir=${OPTARG}
	    ;;
	r)
	    echo "Results destination dir: ${OPTARG}"
	    arg_results_dir=${OPTARG}
	    ;;
	:)
	    echo "Error: -${OPTARG} requires an argument"
	    exit 1
	    ;;
	*)
	    exit 1
	    ;;
    esac
done

. /etc/profile
. $HOME/.bash_profile

module add cuda/11.0

export XLA_FLAGS="--xla_gpu_cuda_data_dir=$CUDA_HOME"


DATEHIGH=`date -d "${arg_date}" +%F`
DATELOW=`date -d "${arg_date} - 84 days" +%F`

echo Date range $DATELOW to $DATEHIGH
poetry run python -m covid_pipeline.pipeline \
      --config ${arg_config} \
      --date-range $DATELOW $DATEHIGH \
      --results-directory ${arg_staging_dir} \
      -v ||
    error_exit "Pipeline job failed"

# Push results to bucket
BASENAME=`basename ${arg_staging_dir}`
BUCKET_DIR=${arg_results_dir}/${BASENAME}

module add aws-cli
aws --endpoint-url https://fhm-chicas-storage.lancs.ac.uk s3 \
    --profile covid-pipeline-data \
    cp --recursive ${arg_staging_dir} ${BUCKET_DIR}

# Trigger report
REPORTBRANCH=master
if [[ `echo ${BASENAME} | cut -d"_" -f2`=="england1" ]]; then
    REPORTBRANCH=england1
fi

curl -X POST \
     -F token=af97c2c166429bf85006261a040886 \
     -F "ref=$REPORTBRANCH" \
     -F "variables[S3TARGET]=${BUCKET_DIR}" \
     https://fhm-chicas-code.lancs.ac.uk/api/v4/projects/163/trigger/pipeline

exit 0
