[tool.poetry]
name = "covid-production-pipeline"
version = "0.1.0"
description = "COVID19 daily production"
authors = ["Chris Jewell <c.jewell@lancaster.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
covid19uk = {git = "git@fhm-chicas-code.lancs.ac.uk:jewell/covid19uk.git", ref="165670639318a2dac2ce4502e6bc67074b5659e6"}

[tool.poetry.dev-dependencies]
ipython = "^7.20.0"
jedi = "^0.17.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
