[tool.poetry]
name = "covid-production-pipeline"
version = "0.1.0"
description = "COVID19 daily production"
authors = ["Chris Jewell <c.jewell@lancaster.ac.uk>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
covid19uk = {git = "git@fhm-chicas-code.lancs.ac.uk:jewell/covid19uk.git", rev="d9c52e4eee49d9befd97db60cca1c58835a73dbd"}
drmaa = "^0.7.9"
jupyter = "^1.0.0"
xarray = {extras = ["netcdf4"], version = "^0.17.0"}
s3fs = "^0.5.2"
jupyterlab = "^3.0.12"
ipympl = "^0.6.3"
zarr = "^2.7.0"
hide-code = "^0.6.0"

[tool.poetry.dev-dependencies]
ipython = "^7.20.0"
jedi = "^0.17.2"
flake8 = "^3.8.4"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
