# Covid stochastic model configuration

ProcessData:
  date_range:
    - 2020-10-09
    - 2021-01-01
  mobility_matrix: data/mergedflows.csv
  population_size: data/c2019modagepop.csv
  commute_volume:   # Can be replaced by DfT traffic flow data - contact authors <c.jewell@lancaster.ac.uk>
  geopackage: data/UK2019mod_pop.gpkg
  
  CasesData:
    input: url
    address: https://api.coronavirus.data.gov.uk/v2/data?areaType=ltla&metric=newCasesBySpecimenDate&format=json
    pillars: None  # Capability to filter Pillar 1 and 2 testing data from PHE confidential line listing
    measure: None  # Capability to filter date of test report from PHE confidential line listing
    format: gov
 
  AreaCodeData:
    input: json
    address: "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LAD_DEC_2019_UK_NC/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=LAD19CD,LAD19NM&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token="
    format: ons
    regions:
      - S  # Scotland
      - E  # England
      - W  # Wales
      - N # Northern Ireland

Mcmc:
  dmax: 84  # Max distance to move events
  nmax: 25  # Max num events per metapopulation/time to move
  m: 1      # Number of metapopulations to move
  occult_nmax: 32  # Max number of occults to add/delete per metapop/time
  num_event_time_updates: 380  # Num event and occult updates per sweep of Gibbs MCMC sampler.
  num_bursts: 200  # Number of MCMC bursts of `num_burst_samples` 
  num_burst_samples: 200  # Number of MCMC samples per burst
  thin: 20  # Thin MCMC samples every `thin` iterations
  num_adaptation_iterations: 1000
  initial_rates:
    ei: 0.5
    ir: 0.5

ThinPosterior:  # Post-process further chain thinning HDF5 -> .pkl.
  start: -10000 
  end:
  by: 10

Geopackage:  # covid.tasks.summary_geopackage
  base_geopackage: data/UK2019mod_pop.gpkg
  base_layer: UK2019mod_pop_xgen
